### PR TITLE
[JENKINS-73427] With 'Accept first connection' host key verification, and JGit, newly added known_hosts entries are malformed

### LINKED ISSUE #1686: [JENKINS-73427] With 'Accept first connection' host key verification, and JGit, newly added known_hosts entries are malformed
<p>I had noticed a lot of errors in our logs surrounding bad known_hosts entries. After some investigation, I was able to reproduce the errors with a minimal example.</p>
<ul>
	<li>Start with the jenkins 2.466 container image, and install just the suggested plugins.</li>
	<li>Change Host Key Verification Configuration to 'Accept First Connection'</li>
	<li>Under tools, change the git installation to JGit</li>
	<li>Create a small pipeline, I used:</li>
</ul>

<pre>
pipeline {
  agent any
  stages {
    stage(<span class="code-quote">'Build'</span>) {
      steps {
        git(url: <span class="code-quote">'git@​github.com:jglick/simple-maven-project-with-tests.git'</span>)
      }
    }
  }
} </pre>

<ul>
	<li>Run once, this example will fail because I'm not using credentials, but simply attempting to connect was enough to populate the known_hosts file.</li>
	<li>Check the known hosts, for me it had one entry</li>
</ul>

<pre>
|1|vHQTSjzHfpTcSNCbqMC6wEt7Mdc=|DtAq017Mv0pQZgijf9OBKbFiXV0=,|1|Y3N48nfiSHdw0U8ks35rVAUT7EM=|x9574xf5oQLevrHV4yulGkk9LOQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= </pre>
<p>Noticing the first part has <b>|1|<blah>|<blah>,|1|<blah>|<blah> ecdsa-sha2-nistp256</b></p>
<ul>
	<li>On a second run, it will cause an error because it can't read the entry, and since it can't find an entry that matches, it creates another invalid entry.</li>
</ul>

<p>It doesn't seem to have a great impact, however it does start to fill up the known_hosts file, and as it grows, the errors in the log grow as well since there is an error for each entry it fails to read:</p>

<pre>
Known hosts file /<span class="code-keyword">var</span>/jenkins_home/.ssh/known_hosts contains invalid line |1|vHQTSjzHfpTcSNCbqMC6wEt7Mdc=|DtAq017Mv0pQZgijf9OBKbFiXV0=,|1|Y3N48nfiSHdw0U8ks35rVAUT7EM=|x9574xf5oQLevrHV4yulGkk9LOQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
java.lang.IllegalArgumentException: Invalid hash pattern (insufficient data): |1|vHQTSjzHfpTcSNCbqMC6wEt7Mdc=|DtAq017Mv0pQZgijf9OBKbFiXV0=,|1|Y3N48nfiSHdw0U8ks35rVAUT7EM=|x9574xf5oQLevrHV4yulGkk9LOQ= </pre>

---
<details><summary><i>Originally reported by  <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mbrunton27">mbrunton27</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-73427" target="_blank">With 'Accept first connection' host key verification, and JGit, newly added known_hosts entries are malformed</a></i></summary>
<i><ul>
<li><b>assignee</b>:  <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=markewaite">markewaite</a>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: git-client-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 20251211-071809
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>I had noticed a lot of errors in our logs surrounding bad known_hosts entries. After some investigation, I was able to reproduce the errors with a minimal example.</p>
<ul>
	<li>Start with the jenkins 2.466 container image, and install just the suggested plugins.</li>
	<li>Change Host Key Verification Configuration to 'Accept First Connection'</li>
	<li>Under tools, change the git installation to JGit</li>
	<li>Create a small pipeline, I used:</li>
</ul>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">pipeline {
  agent any
  stages {
    stage(<span class="code-quote">'Build'</span>) {
      steps {
        git(url: <span class="code-quote">'git@github.com:jglick/simple-maven-project-with-tests.git'</span>)
      }
    }
  }
} </pre>
</div></div>

<ul>
	<li>Run once, this example will fail because I'm not using credentials, but simply attempting to connect was enough to populate the known_hosts file.</li>
	<li>Check the known hosts, for me it had one entry</li>
</ul>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">|1|vHQTSjzHfpTcSNCbqMC6wEt7Mdc=|DtAq017Mv0pQZgijf9OBKbFiXV0=,|1|Y3N48nfiSHdw0U8ks35rVAUT7EM=|x9574xf5oQLevrHV4yulGkk9LOQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= </pre>
</div></div>
<p>Noticing the first part has <b>|1|&lt;blah&gt;|&lt;blah&gt;,|1|&lt;blah&gt;|&lt;blah&gt; ecdsa-sha2-nistp256</b></p>
<ul>
	<li>On a second run, it will cause an error because it can't read the entry, and since it can't find an entry that matches, it creates another invalid entry.</li>
</ul>

<p>It doesn't seem to have a great impact, however it does start to fill up the known_hosts file, and as it grows, the errors in the log grow as well since there is an error for each entry it fails to read:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Known hosts file /<span class="code-keyword">var</span>/jenkins_home/.ssh/known_hosts contains invalid line |1|vHQTSjzHfpTcSNCbqMC6wEt7Mdc=|DtAq017Mv0pQZgijf9OBKbFiXV0=,|1|Y3N48nfiSHdw0U8ks35rVAUT7EM=|x9574xf5oQLevrHV4yulGkk9LOQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
java.lang.IllegalArgumentException: Invalid hash pattern (insufficient data): |1|vHQTSjzHfpTcSNCbqMC6wEt7Mdc=|DtAq017Mv0pQZgijf9OBKbFiXV0=,|1|Y3N48nfiSHdw0U8ks35rVAUT7EM=|x9574xf5oQLevrHV4yulGkk9LOQ= </pre>
</div></div></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Docker image jenkins/jenkins:2.466 with suggested plugins installed. Git client plugin version 5.0.0</code></li></ul>

### PR DESCRIPTION
**Pull request by akash-manna-sky**
Fixes #1686 

[JENKINS-73427](https://issues.jenkins.io/browse/JENKINS-73427)

With 'Accept first connection' host key verification, and JGit, newly added known_hosts entries are malformed

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

**Comment by akash-manna-sky** [comment]
Hello @MarkEWaite, can you please review this PR?

**Comment by MarkEWaite** [comment]
> Hello @MarkEWaite, can you please review this PR?

Needs one or more tests that show the issue and confirm that the issue is resolved by the code change.  In this case, it may be better to not pass the HashKnownHosts argument at all so that users can configure it in their ssh_config if they really want it.  Refer to issue report:

* #1702

**Comment by akash-manna-sky** [comment]
Can you please review the changes? @MarkEWaite

File: src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java [hunk 1]
```diff
@@ -82,9 +83,99 @@ void testVerifyServerHostKeyWhenFirstConnection() throws Exception {
...
+        assumeTrue(runKnownHostsTests());
+        String malformedHashedEntry = KEY_ECDSA_SHA_2_NISTP_256;
+        
+        File mockedKnownHosts = knownHostsTestUtil.createFakeKnownHosts(malformedHashedEntry);
+        AcceptFirstConnectionVerifier acceptFirstConnectionVerifier = spy(new AcceptFirstConnectionVerifier());
+        when(acceptFirstConnectionVerifier.getKnownHostsFile()).thenReturn(mockedKnownHosts);
+
+        // This should not throw an exception when reading the malformed entry
+        // The connection might fail to verify, but it shouldn't crash
+        try {
```
Comment (MarkEWaite) [inline src/test/java/org/jenkinsci/plugins/gitclient/verifier/AcceptFirstConnectionVerifierTest.java]: If it is expected to throw an exception, please use `assertThrows`

**Review by MarkEWaite — COMMENTED** [review]
First review comments.  More in another day

**Comment by akash-manna-sky** [comment]
Please have a look. @MarkEWaite

**Comment by MarkEWaite** [comment]
@akash-manna-sky I would like to test this in my development environment, but I'm not allowed to merge the master branch to it.  Could you merge the master branch into it so that the latest fixes and releases are included?

**Comment by akash-manna-sky** [comment]
> @akash-manna-sky I would like to test this in my development environment, but I'm not allowed to merge the master branch to it. Could you merge the master branch into it so that the latest fixes and releases are included?

I rebase my branch with master branch, so all the latest fixes and releases are included now. You can test it now.

**Comment by MarkEWaite** [comment]
> I rebase my branch with master branch, so all the latest fixes and releases are included now. You can test it now.

Thanks.  Generally it is better to merge rather than rebase in a pull request.  When you rebase, it often disconnects comments from the changes.  The change will be squash merged eventually, so the various steps in the pull request commit history will be collapsed into a single commit on the master branch.

**Comment by akash-manna-sky** [comment]
Have you tested the changes? Please tell me if anything I need to modify or update. @MarkEWaite

**Comment by MarkEWaite** [comment]
> Have you tested the changes? Please tell me if anything I need to modify or update. @MarkEWaite

No issues detected in my testing thus far, but I'm testing mostly by using the plugin in other work.  I will need to do more specific testing by changing the host key verification strategy to look for surprises.

**Comment by akash-manna-sky** [comment]
> > Have you tested the changes? Please tell me if anything I need to modify or update. @MarkEWaite
> 
> No issues detected in my testing thus far, but I'm testing mostly by using the plugin in other work. I will need to do more specific testing by changing the host key verification strategy to look for surprises.

Thanks for testing! That makes sense. I’ll wait for your additional host key verification testing—please let me know if you’d like me to make changes on my side. @MarkEWaite

**Comment by akash-manna-sky** [comment]
Is this PR fine now ? Please let me know if there’s anything I need to update. @MarkEWaite

**Comment by MarkEWaite** [comment]
> Is this PR fine now ? Please let me know if there’s anything I need to update. @MarkEWaite

I'm still testing and exploring.

**Comment by akash-manna-sky** [comment]
It is good to see that my changes have passed all the tests and have been merged. Please assign or suggest me a few issues in this plugin, or in other plugins you maintain, that are higher priority to fix and for which you are willing to accept new pull requests, so that I can continue contributing. I am especially interested in back-end–related tasks. Thank you!

@MarkEWaite

**Comment by MarkEWaite** [comment]
> Please assign or suggest me a few issues in this plugin, or in other plugins you maintain,

No, I won't.  I'm growing weary of your repeated requests.

Please close pull requests that you're not continuing, like:

* https://github.com/jenkinsci/git-client-plugin/pull/1716

Please invest more of your time to deeply test the changes you're proposing.  Describe the ways that you've deeply tested those proposed changes.  Show that you've exhausted all your own ideas for testing the changes that you are proposing.  Then allow time for the maintainers to review them. 

In the case of this specific pull request, there was no clear evidence in the pull request description that you were able to duplicate the issue yourself.  You disabled hashing of the known hosts file, but didn't describe how you had tested it yourself.  I spent multiple hours performing various tests trying to assure that the change is ready to ship.

Please allow changes from maintainers on your pull request branches.  When you disallow changes from maintainers, you make the interaction more complicated for maintainers that are reviewing your proposed changes.

Please reduce the frequency at which you ask for updates.  Most maintainers will ignore you if you request too frequently or they will ask that you be banned from the organization.
